name: Monthly Food Service

on:
  workflow_dispatch:

  # schedule:
  #   - cron: "0 1 15 * *"

jobs:
  submit-food-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run food service automation
        env:
          FORM_URL: ${{ secrets.FORM_URL }}
        run: python -m src.main
